(defvar required-packages
  '(
    magit
    yasnippet
    multiple-cursors
    key-chord
    auto-complete
    ido
    buffer-extension
    autopair
    expand-region
    mark-multiple
    mark-more-like-this
    imenu-anywhere
    undo-tree
    switch-window
    ffap
    etags-select
    json-reformat
    buffer-move
    flymake-cursor
    git-gutter
    restclient
    py-autopep8
    flymake-easy
    flymake-jslint
    flycheck
    flx-ido
    powerline
    flymake
    ag
    dockerfile-mode
    python-mode
    avy
    frame-cmds
    elpy
    markdown-mode
    kooten-theme
    ubuntu-theme
    zenburn-theme
    solarized-theme
    sphinx-doc
    backup-walker
    pytest
    flymake-json
    yaml-mode
    elscreen
    elscreen-persist
    solidity-mode
    tide
    groovy-mode
    typescript
    flymake-solidity
    go-mode
    gorepl-mode
    company-go
    perspective
    projectile
    persp-projectile
    ivy
    pycoverage
    smex
    realgud
    js2-mode
    nodejs-repl
    org
    git-timemachine
    edit-server
    engine-mode
    dired+
    org-bullets
    dired-open
    ido-ubiquitous
    ido-vertical-mode
    wrap-region
    htmlize
    tide
    exec-path-from-shell
    docker-tramp
    vagrant-tramp
    use-package
    yafolding
    discover
    flycheck-gometalinter
    ob-go
    inf-ruby
    company-inf-ruby
    helm-descbinds
    go-guru
    wgrep
    helm-ag
    helm-themes
    monokai-theme
    ample-theme
    json-mode
    go-eldoc
    jq-mode
    jedi
    company-jedi
    robe
    xref-js2
    js2-refactor
    company-tern
    eclim
    php-mode
    org-autolist
    diminish
    jdecomp
    maxframe
    kotlin-mode
    helm-tramp
    ) "a list of packages to ensure are installed at launch.")

(provide 'emp-external-packages)
